# Generated by Django 5.2 on 2025-04-24 09:26

import django.db.models.deletion
import django.utils.timezone
import hope_api_auth.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Key",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "allowed_ips",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="IPs"),
                ),
                ("valid_from", models.DateField(default=django.utils.timezone.now)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "grants",
                    hope_api_auth.fields.ChoiceArrayField(base_field=models.CharField(max_length=255), size=None),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_token",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "swappable": "HOPE_API_AUTH_APITOKEN_MODEL",
            },
        ),
        migrations.CreateModel(
            name="APILogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("url", models.URLField()),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.IntegerField()),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.HOPE_API_AUTH_APITOKEN_MODEL,
                    ),
                ),
            ],
        ),
    ]
